// Curated Mandarin starter vocabulary by skill level. Drawn from HSK 1–4 frequency
// lists, kept short and broadly useful. The onboarding endpoint inserts a slice of
// the appropriate level into the user's deck. Topic tags let us bias selection
// toward what the user said they're interested in (food/travel/work/media).

export const STARTER_VOCAB = {
  zh: {
  beginner: [
    // Greetings & basics
    ['你好', 'nǐ hǎo', 'hello', ['greet']],
    ['谢谢', 'xièxie', 'thank you', ['greet']],
    ['再见', 'zàijiàn', 'goodbye', ['greet']],
    ['对不起', 'duìbuqǐ', "I'm sorry", ['greet']],
    ['不客气', 'bú kèqi', "you're welcome", ['greet']],
    // People & pronouns
    ['我', 'wǒ', 'I / me', ['core']],
    ['你', 'nǐ', 'you', ['core']],
    ['他', 'tā', 'he / him', ['core']],
    ['她', 'tā', 'she / her', ['core']],
    ['朋友', 'péngyǒu', 'friend', ['social']],
    // Verbs
    ['吃', 'chī', 'to eat', ['food']],
    ['喝', 'hē', 'to drink', ['food']],
    ['看', 'kàn', 'to look / watch', ['media']],
    ['听', 'tīng', 'to listen', ['media']],
    ['说', 'shuō', 'to speak', ['core']],
    ['去', 'qù', 'to go', ['travel']],
    ['来', 'lái', 'to come', ['travel']],
    // Objects
    ['水', 'shuǐ', 'water', ['food']],
    ['茶', 'chá', 'tea', ['food']],
    ['饭', 'fàn', 'rice / meal', ['food']],
    ['书', 'shū', 'book', ['media']],
    // Places
    ['家', 'jiā', 'home / family', ['social']],
    ['学校', 'xuéxiào', 'school', ['core']],
    // Adjectives & basics
    ['好', 'hǎo', 'good / well', ['core']],
    ['大', 'dà', 'big', ['core']],
    ['小', 'xiǎo', 'small', ['core']],
    // Time
    ['今天', 'jīntiān', 'today', ['core']],
    ['明天', 'míngtiān', 'tomorrow', ['core']],
    // Numbers
    ['一', 'yī', 'one', ['core']],
    ['二', 'èr', 'two', ['core']],
  ],
  intermediate: [
    ['因为', 'yīnwèi', 'because', ['core']],
    ['所以', 'suǒyǐ', 'therefore', ['core']],
    ['但是', 'dànshì', 'but / however', ['core']],
    ['如果', 'rúguǒ', 'if', ['core']],
    ['已经', 'yǐjīng', 'already', ['core']],
    ['正在', 'zhèngzài', 'in the middle of …ing', ['core']],
    ['可能', 'kěnéng', 'possibly / maybe', ['core']],
    ['决定', 'juédìng', 'to decide', ['core']],
    ['希望', 'xīwàng', 'to hope', ['core']],
    ['觉得', 'juéde', 'to feel / to think', ['core']],
    ['办公室', 'bàngōngshì', 'office', ['work']],
    ['会议', 'huìyì', 'meeting', ['work']],
    ['项目', 'xiàngmù', 'project', ['work']],
    ['同事', 'tóngshì', 'colleague', ['work']],
    ['火车', 'huǒchē', 'train', ['travel']],
    ['飞机', 'fēijī', 'airplane', ['travel']],
    ['酒店', 'jiǔdiàn', 'hotel', ['travel']],
    ['护照', 'hùzhào', 'passport', ['travel']],
    ['菜单', 'càidān', 'menu', ['food']],
    ['餐厅', 'cāntīng', 'restaurant', ['food']],
    ['味道', 'wèidào', 'flavor / taste', ['food']],
    ['辣', 'là', 'spicy', ['food']],
    ['电影', 'diànyǐng', 'movie', ['media']],
    ['歌曲', 'gēqǔ', 'song', ['media']],
    ['歌手', 'gēshǒu', 'singer', ['media']],
    ['音乐', 'yīnyuè', 'music', ['media']],
    ['故事', 'gùshi', 'story', ['media']],
    ['有趣', 'yǒuqù', 'interesting', ['core']],
    ['重要', 'zhòngyào', 'important', ['core']],
    ['马上', 'mǎshàng', 'right away', ['core']],
  ],
  advanced: [
    ['尽管', 'jǐnguǎn', 'even though', ['core']],
    ['毕竟', 'bìjìng', 'after all', ['core']],
    ['似乎', 'sìhū', 'seems as if', ['core']],
    ['倾向', 'qīngxiàng', 'tendency / to lean toward', ['core']],
    ['差异', 'chāyì', 'difference', ['core']],
    ['本质', 'běnzhì', 'essence / nature', ['core']],
    ['现象', 'xiànxiàng', 'phenomenon', ['core']],
    ['趋势', 'qūshì', 'trend', ['work']],
    ['策略', 'cèlüè', 'strategy', ['work']],
    ['资源', 'zīyuán', 'resource', ['work']],
    ['谈判', 'tánpàn', 'negotiation', ['work']],
    ['投资', 'tóuzī', 'investment', ['work']],
    ['企业', 'qǐyè', 'enterprise', ['work']],
    ['行业', 'hángyè', 'industry', ['work']],
    ['市场', 'shìchǎng', 'market', ['work']],
    ['传统', 'chuántǒng', 'tradition', ['social']],
    ['文化', 'wénhuà', 'culture', ['social']],
    ['价值观', 'jiàzhíguān', 'values / value system', ['social']],
    ['观点', 'guāndiǎn', 'point of view', ['core']],
    ['争论', 'zhēnglùn', 'debate', ['core']],
    ['批评', 'pīpíng', 'criticism', ['core']],
    ['赞美', 'zànměi', 'to praise', ['core']],
    ['启发', 'qǐfā', 'inspiration', ['core']],
    ['贡献', 'gòngxiàn', 'contribution', ['core']],
    ['履行', 'lǚxíng', 'to fulfill / carry out', ['core']],
    ['经历', 'jīnglì', 'experience (n./v.)', ['core']],
    ['享受', 'xiǎngshòu', 'to enjoy', ['core']],
    ['挑战', 'tiǎozhàn', 'challenge', ['core']],
    ['机会', 'jīhuì', 'opportunity', ['core']],
    ['追求', 'zhuīqiú', 'to pursue', ['core']],
  ],
  },
  hi: {
    beginner: [
      ['नमस्ते', 'namaste', 'hello', ['greet']],
      ['धन्यवाद', 'dhanyavaad', 'thank you', ['greet']],
      ['अलविदा', 'alavida', 'goodbye', ['greet']],
      ['क्षमा करें', 'kshama karen', 'I am sorry', ['greet']],
      ['आपका स्वागत है', 'aapka swaagat hai', 'you are welcome', ['greet']],
      ['मैं', 'main', 'I / me', ['core']],
      ['तुम', 'tum', 'you', ['core']],
      ['वह', 'vah', 'he / she', ['core']],
      ['दोस्त', 'dost', 'friend', ['social']],
      ['खाना', 'khaana', 'to eat', ['food']],
      ['पीना', 'peena', 'to drink', ['food']],
      ['देखना', 'dekhna', 'to look', ['media']],
      ['सुनना', 'sunna', 'to listen', ['media']],
      ['बोलना', 'bolna', 'to speak', ['core']],
      ['जाना', 'jaana', 'to go', ['travel']],
      ['आना', 'aana', 'to come', ['travel']],
      ['पानी', 'paanee', 'water', ['food']],
      ['चाय', 'chaay', 'tea', ['food']],
      ['चावल', 'chaaval', 'rice', ['food']],
      ['किताब', 'kitaab', 'book', ['media']],
      ['घर', 'ghar', 'home', ['social']],
      ['स्कूल', 'skool', 'school', ['core']],
      ['अच्छा', 'achchha', 'good', ['core']],
      ['बड़ा', 'bada', 'big', ['core']],
      ['छोटा', 'chhota', 'small', ['core']],
      ['आज', 'aaj', 'today', ['core']],
      ['कल', 'kal', 'tomorrow', ['core']],
      ['एक', 'ek', 'one', ['core']],
      ['दो', 'do', 'two', ['core']],
      ['हाँ', 'haan', 'yes', ['core']]
    ],
    intermediate: [
      ['क्योंकि', 'kyonki', 'because', ['core']],
      ['इसलिए', 'isalie', 'therefore', ['core']],
      ['लेकिन', 'lekin', 'but', ['core']],
      ['अगर', 'agar', 'if', ['core']],
      ['पहले से', 'pahale se', 'already', ['core']],
      ['शायद', 'shaayad', 'perhaps', ['core']],
      ['तय करना', 'tay karna', 'to decide', ['core']],
      ['उम्मीद', 'ummeed', 'hope', ['core']],
      ['महसूस करना', 'mahasoos karna', 'to feel', ['core']],
      ['दफ़्तर', 'daftar', 'office', ['work']],
      ['बैठक', 'baithak', 'meeting', ['work']],
      ['प्रोजेक्ट', 'projekt', 'project', ['work']],
      ['सहकर्मी', 'sahakarmee', 'colleague', ['work']],
      ['ट्रेन', 'tren', 'train', ['travel']],
      ['हवाई जहाज़', 'havaee jahaaz', 'airplane', ['travel']],
      ['होटल', 'hotal', 'hotel', ['travel']],
      ['पासपोर्ट', 'paasaport', 'passport', ['travel']],
      ['मेन्यू', 'menyu', 'menu', ['food']],
      ['रेस्तरां', 'restaraan', 'restaurant', ['food']],
      ['स्वाद', 'svaad', 'flavor', ['food']],
      ['मसालेदार', 'masaledaar', 'spicy', ['food']],
      ['फ़िल्म', 'film', 'movie', ['media']],
      ['गाना', 'gaana', 'song', ['media']],
      ['गायक', 'gaayak', 'singer', ['media']],
      ['संगीत', 'sangeet', 'music', ['media']],
      ['कहानी', 'kahaanee', 'story', ['media']],
      ['दिलचस्प', 'dilachasp', 'interesting', ['core']],
      ['ज़रूरी', 'zarooree', 'important', ['core']],
      ['तुरंत', 'turant', 'immediately', ['core']],
      ['वक्त', 'vakt', 'time', ['core']]
    ],
    advanced: [
      ['हालांकि', 'haalaanki', 'although', ['core']],
      ['आखिरकार', 'aakhirakaar', 'after all', ['core']],
      ['प्रतीत होना', 'prateet hona', 'to seem', ['core']],
      ['प्रवृत्ति', 'pravrtti', 'tendency', ['core']],
      ['अंतर', 'antar', 'difference', ['core']],
      ['सार', 'saar', 'essence', ['core']],
      ['घटना', 'ghatana', 'phenomenon', ['core']],
      ['रुझान', 'ruzhaan', 'trend', ['work']],
      ['रणनीति', 'rananeeti', 'strategy', ['work']],
      ['संसाधन', 'sansaadhan', 'resource', ['work']],
      ['बातचीत', 'baatacheet', 'negotiation', ['work']],
      ['निवेश', 'nivesh', 'investment', ['work']],
      ['उद्यम', 'udyam', 'enterprise', ['work']],
      ['उद्योग', 'udyog', 'industry', ['work']],
      ['बाज़ार', 'baazaar', 'market', ['work']],
      ['परंपरा', 'parampara', 'tradition', ['social']],
      ['संस्कृति', 'sanskrti', 'culture', ['social']],
      ['मूल्य', 'mooly', 'values', ['social']],
      ['दृष्टिकोण', 'drshtikon', 'point of view', ['core']],
      ['बहस', 'bahas', 'debate', ['core']],
      ['आलोचना', 'aalochna', 'criticism', ['core']],
      ['प्रशंसा', 'prashansa', 'praise', ['core']],
      ['प्रेरणा', 'prerana', 'inspiration', ['core']],
      ['योगदान', 'yogadaan', 'contribution', ['core']],
      ['निभाना', 'nibhaana', 'to fulfill', ['core']],
      ['अनुभव', 'anubhav', 'experience', ['core']],
      ['आनंद लेना', 'aanand lena', 'to enjoy', ['core']],
      ['चुनौती', 'chunoutee', 'challenge', ['core']],
      ['अवसर', 'avasar', 'opportunity', ['core']],
      ['पीछा करना', 'peecha karna', 'to pursue', ['core']]
    ]
  },
  fr: {
    beginner: [
      ['bonjour', 'bɔ̃.ʒuʁ', 'hello', ['greet']],
      ['merci', 'mɛʁ.si', 'thank you', ['greet']],
      ['au revoir', 'o ʁə.vwaʁ', 'goodbye', ['greet']],
      ['pardon', 'paʁ.dɔ̃', 'sorry', ['greet']],
      ['de rien', 'də ʁjɛ̃', 'you are welcome', ['greet']],
      ['je', 'ʒə', 'I', ['core']],
      ['tu', 'ty', 'you', ['core']],
      ['il', 'il', 'he', ['core']],
      ['elle', 'ɛl', 'she', ['core']],
      ['ami', 'a.mi', 'friend', ['social']],
      ['manger', 'mɑ̃.ʒe', 'to eat', ['food']],
      ['boire', 'bwaʁ', 'to drink', ['food']],
      ['regarder', 'ʁə.ɡaʁ.de', 'to look', ['media']],
      ['écouter', 'e.ku.te', 'to listen', ['media']],
      ['parler', 'paʁ.le', 'to speak', ['core']],
      ['aller', 'a.le', 'to go', ['travel']],
      ['venir', 'və.niʁ', 'to come', ['travel']],
      ['eau', 'o', 'water', ['food']],
      ['café', 'ka.fe', 'coffee', ['food']],
      ['pain', 'pɛ̃', 'bread', ['food']],
      ['livre', 'livʁ', 'book', ['media']],
      ['maison', 'mɛ.zɔ̃', 'home', ['social']],
      ['école', 'e.kɔl', 'school', ['core']],
      ['bon', 'bɔ̃', 'good', ['core']],
      ['grand', 'ɡʁɑ̃', 'big', ['core']],
      ['petit', 'pə.ti', 'small', ['core']],
      ["aujourd'hui", 'o.ʒuʁ.dɥi', 'today', ['core']],
      ['demain', 'də.mɛ̃', 'tomorrow', ['core']],
      ['un', 'œ̃', 'one', ['core']],
      ['deux', 'dø', 'two', ['core']]
    ],
    intermediate: [
      ['parce que', 'paʁs kə', 'because', ['core']],
      ['donc', 'dɔ̃k', 'therefore', ['core']],
      ['mais', 'mɛ', 'but', ['core']],
      ['si', 'si', 'if', ['core']],
      ['déjà', 'de.ʒa', 'already', ['core']],
      ['peut-être', 'pø.tɛtʁ', 'perhaps', ['core']],
      ['décider', 'de.si.de', 'to decide', ['core']],
      ['espérer', 'ɛs.pe.ʁe', 'to hope', ['core']],
      ['sentir', 'sɑ̃.tiʁ', 'to feel', ['core']],
      ['bureau', 'by.ʁo', 'office', ['work']],
      ['réunion', 'ʁe.y.njɔ̃', 'meeting', ['work']],
      ['projet', 'pʁɔ.ʒɛ', 'project', ['work']],
      ['collègue', 'kɔ.lɛɡ', 'colleague', ['work']],
      ['train', 'tʁɛ̃', 'train', ['travel']],
      ['avion', 'a.vjɔ̃', 'airplane', ['travel']],
      ['hôtel', 'o.tɛl', 'hotel', ['travel']],
      ['passeport', 'pas.pɔʁ', 'passport', ['travel']],
      ['menu', 'mə.ny', 'menu', ['food']],
      ['restaurant', 'ʁɛs.tɔ.ʁɑ̃', 'restaurant', ['food']],
      ['goût', 'ɡu', 'flavor', ['food']],
      ['épicé', 'e.pi.se', 'spicy', ['food']],
      ['film', 'film', 'movie', ['media']],
      ['chanson', 'ʃɑ̃.sɔ̃', 'song', ['media']],
      ['chanteur', 'ʃɑ̃.tœʁ', 'singer', ['media']],
      ['musique', 'my.zik', 'music', ['media']],
      ['histoire', 'is.twaʁ', 'story', ['media']],
      ['intéressant', 'ɛ̃.te.ʁɛ.sɑ̃', 'interesting', ['core']],
      ['important', 'ɛ̃.pɔʁ.tɑ̃', 'important', ['core']],
      ['tout de suite', 'tu də sɥit', 'immediately', ['core']],
      ['temps', 'tɑ̃', 'time', ['core']]
    ],
    advanced: [
      ['bien que', 'bjɛ̃ kə', 'although', ['core']],
      ['après tout', 'a.pʁɛ tu', 'after all', ['core']],
      ['sembler', 'sɑ̃.ble', 'to seem', ['core']],
      ['tendance', 'tɑ̃.dɑ̃s', 'tendency', ['core']],
      ['différence', 'di.fe.ʁɑ̃s', 'difference', ['core']],
      ['essence', 'e.sɑ̃s', 'essence', ['core']],
      ['phénomène', 'fe.nɔ.mɛn', 'phenomenon', ['core']],
      ['courant', 'ku.ʁɑ̃', 'trend', ['work']],
      ['stratégie', 'stʁa.te.ʒi', 'strategy', ['work']],
      ['ressource', 'ʁə.suʁs', 'resource', ['work']],
      ['négociation', 'ne.ɡɔ.sja.sjɔ̃', 'negotiation', ['work']],
      ['investissement', 'ɛ̃.vɛs.tis.mɑ̃', 'investment', ['work']],
      ['entreprise', 'ɑ̃.tʁə.pʁiz', 'enterprise', ['work']],
      ['industrie', 'ɛ̃.dys.tʁi', 'industry', ['work']],
      ['marché', 'maʁ.ʃe', 'market', ['work']],
      ['tradition', 'tʁa.di.sjɔ̃', 'tradition', ['social']],
      ['culture', 'kyl.tyʁ', 'culture', ['social']],
      ['valeurs', 'va.lœʁ', 'values', ['social']],
      ['point de vue', 'pwɛ̃ də vy', 'point of view', ['core']],
      ['débat', 'de.ba', 'debate', ['core']],
      ['critique', 'kʁi.tik', 'criticism', ['core']],
      ['éloge', 'e.lɔʒ', 'praise', ['core']],
      ['inspiration', 'ɛ̃s.pi.ʁa.sjɔ̃', 'inspiration', ['core']],
      ['contribution', 'kɔ̃.tʁi.by.sjɔ̃', 'contribution', ['core']],
      ['accomplir', 'a.kɔ̃.pliʁ', 'to fulfill', ['core']],
      ['expérience', 'ɛk.spe.ʁjɑ̃s', 'experience', ['core']],
      ['profiter', 'pʁɔ.fi.te', 'to enjoy', ['core']],
      ['défi', 'de.fi', 'challenge', ['core']],
      ['opportunité', 'ɔ.pɔʁ.ty.ni.te', 'opportunity', ['core']],
      ['poursuivre', 'puʁ.sɥivʁ', 'to pursue', ['core']]
    ]
  },
  es: {
    beginner: [
      ['hola', 'o.la', 'hello', ['greet']],
      ['gracias', 'gɾa.sjas', 'thank you', ['greet']],
      ['adiós', 'a.djos', 'goodbye', ['greet']],
      ['lo siento', 'lo sjen.to', 'sorry', ['greet']],
      ['de nada', 'de na.ða', 'you are welcome', ['greet']],
      ['yo', 'ʝo', 'I', ['core']],
      ['tú', 'tu', 'you', ['core']],
      ['él', 'el', 'he', ['core']],
      ['ella', 'e.ʝa', 'she', ['core']],
      ['amigo', 'a.mi.ɣo', 'friend', ['social']],
      ['comer', 'ko.meɾ', 'to eat', ['food']],
      ['beber', 'be.βeɾ', 'to drink', ['food']],
      ['mirar', 'mi.ɾaɾ', 'to look', ['media']],
      ['escuchar', 'es.ku.tʃaɾ', 'to listen', ['media']],
      ['hablar', 'a.βlaɾ', 'to speak', ['core']],
      ['ir', 'iɾ', 'to go', ['travel']],
      ['venir', 'be.niɾ', 'to come', ['travel']],
      ['agua', 'a.ɣwa', 'water', ['food']],
      ['café', 'ka.fe', 'coffee', ['food']],
      ['pan', 'pan', 'bread', ['food']],
      ['libro', 'li.βɾo', 'book', ['media']],
      ['casa', 'ka.sa', 'home', ['social']],
      ['escuela', 'es.kwe.la', 'school', ['core']],
      ['bueno', 'bwe.no', 'good', ['core']],
      ['grande', 'gɾan.de', 'big', ['core']],
      ['pequeño', 'pe.ke.ɲo', 'small', ['core']],
      ['hoy', 'oi', 'today', ['core']],
      ['mañana', 'ma.ɲa.na', 'tomorrow', ['core']],
      ['uno', 'u.no', 'one', ['core']],
      ['dos', 'dos', 'two', ['core']]
    ],
    intermediate: [
      ['porque', 'poɾ.ke', 'because', ['core']],
      ['por lo tanto', 'poɾ lo tan.to', 'therefore', ['core']],
      ['pero', 'pe.ɾo', 'but', ['core']],
      ['si', 'si', 'if', ['core']],
      ['ya', 'ʝa', 'already', ['core']],
      ['tal vez', 'tal βes', 'perhaps', ['core']],
      ['decidir', 'de.si.ðiɾ', 'to decide', ['core']],
      ['esperar', 'es.pe.ɾaɾ', 'to hope', ['core']],
      ['sentir', 'sen.tiɾ', 'to feel', ['core']],
      ['oficina', 'o.fi.si.na', 'office', ['work']],
      ['reunión', 'reu.njon', 'meeting', ['work']],
      ['proyecto', 'pɾo.ʝek.to', 'project', ['work']],
      ['colega', 'ko.le.ɣa', 'colleague', ['work']],
      ['tren', 'tɾen', 'train', ['travel']],
      ['avión', 'a.βjon', 'airplane', ['travel']],
      ['hotel', 'o.tel', 'hotel', ['travel']],
      ['pasaporte', 'pa.sa.poɾ.te', 'passport', ['travel']],
      ['menú', 'me.nu', 'menu', ['food']],
      ['restaurante', 'res.tau.ɾan.te', 'restaurant', ['food']],
      ['sabor', 'sa.βoɾ', 'flavor', ['food']],
      ['picante', 'pi.kan.te', 'spicy', ['food']],
      ['película', 'pe.li.ku.la', 'movie', ['media']],
      ['canción', 'kan.sjon', 'song', ['media']],
      ['cantante', 'kan.tan.te', 'singer', ['media']],
      ['música', 'mu.si.ka', 'music', ['media']],
      ['historia', 'is.to.ɾja', 'story', ['media']],
      ['interesante', 'in.te.ɾe.san.te', 'interesting', ['core']],
      ['importante', 'im.poɾ.tan.te', 'important', ['core']],
      ['inmediatamente', 'in.me.ðja.ta.men.te', 'immediately', ['core']],
      ['tiempo', 'tjem.po', 'time', ['core']]
    ],
    advanced: [
      ['aunque', 'aun.ke', 'although', ['core']],
      ['después de todo', 'des.pwes de to.ðo', 'after all', ['core']],
      ['parecer', 'pa.ɾe.seɾ', 'to seem', ['core']],
      ['tendencia', 'ten.den.sja', 'tendency', ['core']],
      ['diferencia', 'di.fe.ɾen.sja', 'difference', ['core']],
      ['esencia', 'e.sen.sja', 'essence', ['core']],
      ['fenómeno', 'fe.no.me.no', 'phenomenon', ['core']],
      ['corriente', 'ko.rjen.te', 'trend', ['work']],
      ['estrategia', 'es.tɾa.te.xja', 'strategy', ['work']],
      ['recurso', 're.kuɾ.so', 'resource', ['work']],
      ['negociación', 'ne.ɣo.sja.sjon', 'negotiation', ['work']],
      ['inversión', 'im.beɾ.sjon', 'investment', ['work']],
      ['empresa', 'em.pɾe.sa', 'enterprise', ['work']],
      ['industria', 'in.dus.tɾja', 'industry', ['work']],
      ['mercado', 'meɾ.ka.ðo', 'market', ['work']],
      ['tradición', 'tɾa.ði.sjon', 'tradition', ['social']],
      ['cultura', 'kul.tu.ɾa', 'culture', ['social']],
      ['valores', 'ba.lo.ɾes', 'values', ['social']],
      ['punto de vista', 'pun.to de βis.ta', 'point of view', ['core']],
      ['debate', 'de.βa.te', 'debate', ['core']],
      ['crítica', 'kɾi.ti.ka', 'criticism', ['core']],
      ['elogio', 'e.lo.xjo', 'praise', ['core']],
      ['inspiración', 'ins.pi.ɾa.sjon', 'inspiration', ['core']],
      ['contribución', 'kon.tɾi.βu.sjon', 'contribution', ['core']],
      ['cumplir', 'kum.pliɾ', 'to fulfill', ['core']],
      ['experiencia', 'eks.pe.ɾjen.sja', 'experience', ['core']],
      ['disfrutar', 'dis.fɾu.taɾ', 'to enjoy', ['core']],
      ['desafío', 'de.sa.fi.o', 'challenge', ['core']],
      ['oportunidad', 'o.poɾ.tu.ni.ðað', 'opportunity', ['core']],
      ['perseguir', 'peɾ.se.ɣiɾ', 'to pursue', ['core']]
    ]
  }
};


export const VALID_LEVELS = ['beginner', 'intermediate', 'advanced'];
export const VALID_TOPICS = ['food', 'travel', 'work', 'media', 'social'];

export const BEGINNER_SCENE_PACKS = [
  {
    key: 'people',
    label: 'Meet someone',
    expressions: ['我', '你', '他', '她', '朋友', '你好'],
    examples: {
      我: ['我是学生。', 'I am a student.'],
      你: ['你好吗？', 'How are you?'],
      他: ['他是我的朋友。', 'He is my friend.'],
      她: ['她是我的朋友。', 'She is my friend.'],
      朋友: ['这是我的朋友。', 'This is my friend.'],
      你好: ['你好！', 'Hello!'],
    },
  },
  {
    key: 'drink',
    label: 'Choose a drink',
    expressions: ['喝', '水', '茶', '吃', '饭', '好'],
    examples: {
      喝: ['我喝水。', 'I drink water.'],
      水: ['我要水。', 'I would like water.'],
      茶: ['我要喝茶。', 'I would like to drink tea.'],
      吃: ['我吃饭。', 'I eat a meal.'],
      饭: ['这个饭很好。', 'This meal is good.'],
      好: ['这个茶很好。', 'This tea is good.'],
    },
  },
  {
    key: 'movement',
    label: 'Go somewhere',
    expressions: ['去', '来', '家', '学校', '今天', '明天'],
    examples: {
      去: ['我去学校。', 'I go to school.'],
      来: ['你来我家。', 'You come to my home.'],
      家: ['我回家。', 'I go home.'],
      学校: ['学校很大。', 'The school is big.'],
      今天: ['我今天去学校。', 'I go to school today.'],
      明天: ['我明天回家。', 'I go home tomorrow.'],
    },
  },
];
